services:
  db:
    container_name: desafio-db
    image: postgres:latest
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db: