# Generated by Django 5.2.3 on 2025-07-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_atendimento_observacao_atendimento_solucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='resolvido_em',
            field=models.DateTimeField(null=True),
        ),
    ]
