# Generated by Django 5.2.3 on 2025-07-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_atendimento_resolvido_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servico', to='api.servico'),
        ),
    ]
