# Generated by Django 5.2.3 on 2025-07-21 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_atendimento_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteracaoAtencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('tipoUsuario', models.CharField(choices=[('S', 'Solicitante'), ('A', 'Atendente')], max_length=1)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimentoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento', to='api.setor')),
            ],
        ),
    ]
