# Generated by Django 5.2.3 on 2025-07-21 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_interacaoatencimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacaoatencimento',
            name='atendimentoId',
        ),
        migrations.AddField(
            model_name='interacaoatencimento',
            name='atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento', to='api.atendimento'),
        ),
    ]
