# Generated by Django 5.2.3 on 2025-08-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_interacaoatencimento_atendimentoid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwEstatatisticasSetorGenero',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('setor_id', models.IntegerField()),
                ('setor_nome', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_estatistica_setor_genero',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='avaliado',
            field=models.BooleanField(default=False),
        ),
    ]
